package modelo;
// Generated 20:39:19, 28 de feb. de 2023 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccMovement generated by hbm2java
 */
@Entity
@Table(name = "ACC_MOVEMENT", catalog = "empresa")
public class AccMovement implements java.io.Serializable {

	private Integer accountMovId;
	private Account accountByAccountDestId;
	private Account accountByAccountOriginId;
	private BigDecimal amount;
	private Date datetime;

	public AccMovement() {
	}

	public AccMovement(Account accountByAccountDestId, Account accountByAccountOriginId, BigDecimal amount,
			Date datetime) {
		this.accountByAccountDestId = accountByAccountDestId;
		this.accountByAccountOriginId = accountByAccountOriginId;
		this.amount = amount;
		this.datetime = datetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCOUNT_MOV_ID", unique = true, nullable = false)
	public Integer getAccountMovId() {
		return this.accountMovId;
	}

	public void setAccountMovId(Integer accountMovId) {
		this.accountMovId = accountMovId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_DEST_ID", nullable = false)
	public Account getAccountByAccountDestId() {
		return this.accountByAccountDestId;
	}

	public void setAccountByAccountDestId(Account accountByAccountDestId) {
		this.accountByAccountDestId = accountByAccountDestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ORIGIN_ID", nullable = false)
	public Account getAccountByAccountOriginId() {
		return this.accountByAccountOriginId;
	}

	public void setAccountByAccountOriginId(Account accountByAccountOriginId) {
		this.accountByAccountOriginId = accountByAccountOriginId;
	}

	@Column(name = "AMOUNT", nullable = false, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME", nullable = false, length = 23)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
