package modelo;
// Generated 20:39:19, 28 de feb. de 2023 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Partido generated by hbm2java
 */
@Entity
@Table(name = "PARTIDO", catalog = "empresa", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Partido implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private float porcentaje;
	private int numeroVotos;

	public Partido() {
	}

	public Partido(String nombre, float porcentaje, int numeroVotos) {
		this.nombre = nombre;
		this.porcentaje = porcentaje;
		this.numeroVotos = numeroVotos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", nullable = false, precision = 24, scale = 0)
	public float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "numero_votos", nullable = false)
	public int getNumeroVotos() {
		return this.numeroVotos;
	}

	public void setNumeroVotos(int numeroVotos) {
		this.numeroVotos = numeroVotos;
	}

}
