package modelo;
// Generated 20:39:19, 28 de feb. de 2023 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "PROJECT", catalog = "empresa")
public class Project implements java.io.Serializable {

	private Integer projno;
	private String projname;
	private Set<Emp> emps = new HashSet<Emp>(0);

	public Project() {
	}

	public Project(String projname) {
		this.projname = projname;
	}

	public Project(String projname, Set<Emp> emps) {
		this.projname = projname;
		this.emps = emps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PROJNO", unique = true, nullable = false)
	public Integer getProjno() {
		return this.projno;
	}

	public void setProjno(Integer projno) {
		this.projno = projno;
	}

	@Column(name = "PROJNAME", nullable = false, length = 50)
	public String getProjname() {
		return this.projname;
	}

	public void setProjname(String projname) {
		this.projname = projname;
	}





	@ManyToMany(mappedBy = "projects")
	public Set<Emp> getEmps() {
		return this.emps;
	}





	
	public void setEmps(Set<Emp> emps) {
		this.emps = emps;
	}

}
